# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170529_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_dish',
            field=models.CharField(max_length=128),
        ),
    ]
