# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20170529_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_item',
            field=models.ImageField(default=2, upload_to='image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
