# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_item_photo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('time_order', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
