# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.CharField(max_length=128),
        ),
    ]
