# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_order_item_num_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Order_Item',
        ),
    ]
