# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20170601_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.IntegerField(),
        ),
    ]
