# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_order_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
    ]
