# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20170601_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
