# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_oi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oi',
            name='id_item',
        ),
        migrations.DeleteModel(
            name='OI',
        ),
    ]
