# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20170603_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_item',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
